from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
urlpatterns = [
    
    path('',views.main,name='main'),
    path('register/',views.register, name="register"),
    path('Edit-user-EN/',views.edit, name='new'),
    path('Edit-user-AR/',views.edit, name='new-ar'),
    path('user-EN/',views.userr,name='userr'),
    path('log-en/',views.log,name='log'),
    path('log-ar/',views.log,name='log-ar'),
    path('code/',views.membership,name='member'),
    path('member/',views.code, name='code'),
    path('logout/',views.logout_user,name="logout"),
    path('password/', auth_views.LogoutView.as_view()),
    path('search/',views.search , name='search'),
    path('#Services',views.serv,name='serv'),
    path('A/',views.student,name="School A-Student"),
    path('B/',views.student,name="School B-Student"),
    path('C/',views.student,name="School C-Student"),
    path('<str:name>/<int:id>',views.ex1,name='Examss'),
    path('into/<str:name>/<int:id>/', views.e_Q, name='Q'),
    path('marks/',views.Marks,name='marks'),
    path('AR',views.main_ar,name='m-ar'),
    path('exams/',views.sch1_exams, name='s1exam'),
    path('user-AR',views.user_ar, name='user-ar'),
    path('A/',views.student,name="School A-Teacher"),
    path('B/',views.student,name="School B-Teacher"),
    path('C/',views.student,name="School C-Teacher"),
    path('add/',views.Addview,name="add"),
    path('sub-add/',views.Add,name="subadd"),
    path('infoadd/',views.AddExam,name="AddExam"),
    path('quizform/',views.Quizform,name="Qform"),
    path('videoform/',views.AddVideo,name="AddVideo"),
    path('A-ar/',views.student,name="School A-Student-ar"),
    path('B-ar/',views.student,name="School B-Student-ar"),
    path('C-ar/',views.student,name="School C-Student-ar"),
    path('exams-ar/',views.sch1_exams, name='s1exam-ar'),
    path('add-ar/',views.Addview,name="add-ar"),
    path('marks-ar/',views.Marks,name='marks-ar'),
    path('A-ar/',views.student,name="School A-Teacher-ar"),
    path('B-ar/',views.student,name="School B-Teacher-ar"),
    path('C-ar/',views.student,name="School C-Teacher-ar"),
    path('<str:name>/<int:id>-ar',views.ex1,name='Examss-ar'),
    path('into/<str:name>/<int:id>-ar/', views.e_Q, name='Q-ar'),
    path('sub-add-ar/',views.Add,name="subadd-ar"),
    path('infoadd-ar/',views.AddExam,name="AddExam-ar"),
    path('quizform-ar/',views.Quizform,name="Qform-ar"),
    path('videoform-ar/',views.AddVideo,name="AddVideo-ar"),
    path('join/',views.join,name="join"),
]
