# Generated by Django 4.2.2 on 2023-07-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('school', models.CharField(max_length=64)),
                ('password', models.IntegerField()),
            ],
        ),
    ]
