<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-07-20 01:39

from django.db import migrations, models
=======
# Generated by Django 4.2.2 on 2023-10-15 22:28

from django.db import migrations, models
import django.db.models.deletion
>>>>>>> web50/projects/2020/x/capstone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=40, null=True)),
                ('title', models.CharField(max_length=200)),
                ('vedio', models.CharField(max_length=2000)),
                ('link', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=80, null=True)),
                ('name', models.CharField(max_length=100)),
                ('fullmark', models.FloatField()),
                ('quizsnumber', models.IntegerField(null=True)),
                ('half', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('exam_name', models.CharField(max_length=100)),
                ('mark', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School_Name', models.CharField(max_length=64)),
                ('Students_Num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
>>>>>>> web50/projects/2020/x/capstone
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
<<<<<<< HEAD
                ('school', models.CharField(max_length=64)),
                ('password', models.IntegerField()),
=======
                ('password', models.IntegerField()),
                ('rule', models.CharField(choices=[('S', 'Student'), ('T', 'Teacher')], max_length=1, null=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='minelog.schools')),
            ],
        ),
        migrations.CreateModel(
            name='ExamQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('qmark', models.FloatField()),
                ('opt1id', models.IntegerField(null=True)),
                ('opt2id', models.IntegerField(null=True)),
                ('examid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Examid', to='minelog.exam')),
>>>>>>> web50/projects/2020/x/capstone
            ],
        ),
    ]
