# Generated by Django 4.2.2 on 2023-12-13 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minelog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='minelog.students'),
        ),
    ]
