# Generated by Django 4.2.2 on 2023-07-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minelog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School_Name', models.CharField(max_length=64)),
                ('Students_Num', models.IntegerField()),
            ],
        ),
    ]
