# Generated by Django 4.2.2 on 2023-12-13 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minelog', '0002_content_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examowner', to='minelog.students'),
        ),
        migrations.AlterField(
            model_name='content',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contentowner', to='minelog.students'),
        ),
    ]
