# Generated by Django 4.2.2 on 2023-07-20 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minelog', '0002_schools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='minelog.schools'),
        ),
    ]
