# Generated by Django 4.2.2 on 2023-07-22 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minelog', '0004_exammark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exammark',
            old_name='Mark',
            new_name='mark',
        ),
    ]
