# Generated by Django 4.2.2 on 2023-09-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minelog', '0005_rename_mark_exammark_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('vedio', models.CharField(max_length=2000)),
                ('link', models.CharField(max_length=2000)),
            ],
        ),
    ]
