# Generated by Django 4.2.2 on 2023-12-18 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minelog', '0006_alter_students_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammark',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='markowner', to='minelog.students'),
        ),
    ]
