# Generated by Django 4.2.2 on 2023-12-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minelog', '0007_alter_exammark_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammark',
            name='fullmark',
            field=models.IntegerField(null=True),
        ),
    ]
