# Generated by Django 4.2.2 on 2023-09-06 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minelog', '0007_content_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fullmark', models.IntegerField()),
                ('half', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='minelog.schools'),
        ),
        migrations.CreateModel(
            name='ExamQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('qmark', models.IntegerField()),
                ('examid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Examid', to='minelog.exam')),
            ],
        ),
    ]
