# Generated by Django 4.2.2 on 2023-09-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minelog', '0008_exam_alter_students_school_examq'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='category',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
