# Generated by Django 4.2.2 on 2023-12-19 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minelog', '0008_exammark_fullmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schoolcontent', to='minelog.schools'),
        ),
        migrations.AddField(
            model_name='exam',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schoolexams', to='minelog.schools'),
        ),
        migrations.AddField(
            model_name='exammark',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schoolmarks', to='minelog.schools'),
        ),
    ]
