# Generated by Django 4.2.2 on 2023-12-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minelog', '0009_content_school_exam_school_exammark_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
