# Generated by Django 4.2.2 on 2023-09-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minelog', '0010_examq_opt1id_examq_opt2id'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='rule',
            field=models.CharField(choices=[('S', 'Student'), ('T', 'Teacher')], max_length=1, null=True),
        ),
    ]
