# Generated by Django 4.2.2 on 2023-12-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minelog', '0010_students_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='arkeyword',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='artitle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='arname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
