# Generated by Django 4.2.2 on 2024-03-22 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minelog', '0011_content_arkeyword_content_artitle_exam_arname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='arkeyword',
        ),
        migrations.RemoveField(
            model_name='content',
            name='artitle',
        ),
        migrations.RemoveField(
            model_name='schools',
            name='Students_Num',
        ),
    ]
