# Generated by Django 4.2.2 on 2024-12-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minelog', '0013_schools_flex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='flex',
            field=models.CharField(choices=[('Pu', 'public'), ('Pr', 'private')], max_length=2, null=True),
        ),
    ]
